/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamsIndexRouteImport } from './routes/streams/index'
import { Route as StreamsSearchRouteImport } from './routes/streams/search'
import { Route as StreamsStreamIdRouteImport } from './routes/streams/$streamId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIndexRoute = StreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsSearchRoute = StreamsSearchRouteImport.update({
  id: '/streams/search',
  path: '/streams/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsStreamIdRoute = StreamsStreamIdRouteImport.update({
  id: '/streams/$streamId',
  path: '/streams/$streamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/streams/search': typeof StreamsSearchRoute
  '/streams': typeof StreamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/streams/search': typeof StreamsSearchRoute
  '/streams': typeof StreamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/streams/search': typeof StreamsSearchRoute
  '/streams/': typeof StreamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/streams/$streamId'
    | '/streams/search'
    | '/streams'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/streams/$streamId' | '/streams/search' | '/streams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/streams/$streamId'
    | '/streams/search'
    | '/streams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StreamsStreamIdRoute: typeof StreamsStreamIdRoute
  StreamsSearchRoute: typeof StreamsSearchRoute
  StreamsIndexRoute: typeof StreamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/': {
      id: '/streams/'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof StreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/search': {
      id: '/streams/search'
      path: '/streams/search'
      fullPath: '/streams/search'
      preLoaderRoute: typeof StreamsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/$streamId': {
      id: '/streams/$streamId'
      path: '/streams/$streamId'
      fullPath: '/streams/$streamId'
      preLoaderRoute: typeof StreamsStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StreamsStreamIdRoute: StreamsStreamIdRoute,
  StreamsSearchRoute: StreamsSearchRoute,
  StreamsIndexRoute: StreamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
